from pydantic import BaseModel, Field
from typing import List, Union
import uuid


class MinimalSource(BaseModel):
    """Represents a retrieved document source and its location metadata.

    This model stores the information required to identify a text fragment
    extracted from a source file, including its path, character boundaries,
    and optional content.

    Attributes:
        file_path: Path of the original file containing the text fragment.
        first_character_index: Starting character position of the fragment in
            the original file.
        last_character_index: Ending character position of the fragment in the
            original file.
        text: Optional text content of the extracted fragment.
    """

    file_path: str
    first_character_index: int
    last_character_index: int
    text: str | None = None


class UnansweredQuestion(BaseModel):
    """Represents a question without an associated generated answer.

    This model is used to store questions from a dataset before the retrieval
    and answer generation stages have been completed.

    Attributes:
        question_id: Unique identifier assigned automatically to the question.
        question: Text content of the question.
    """

    question_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    question: str


class AnsweredQuestion(UnansweredQuestion):
    """Represents a question with its expected sources and answer.

    This model extends an unanswered question by adding the reference sources
    used to answer it and the expected answer text.

    Attributes:
        sources: List of source fragments containing the information required
            to answer the question.
        answer: Expected answer associated with the question.
    """

    sources: List[MinimalSource]
    answer: str


class RagDataset(BaseModel):
    """Represents a dataset containing RAG evaluation questions.

    The dataset can contain both unanswered questions, used for retrieval or
    generation tasks, and answered questions, used for evaluation.

    Attributes:
        rag_questions: List of questions included in the RAG dataset.
    """

    rag_questions: List[Union[AnsweredQuestion, UnansweredQuestion]]


class MinimalSearchResults(BaseModel):
    """Represents the result of retrieving relevant document sources.

    This model stores the original question together with the document
    fragments retrieved by the search component.

    Attributes:
        question_id: Identifier of the associated question.
        question: Original question text used for retrieval.
        retrieved_sources: List of document fragments returned by the
            retrieval system.
    """

    question_id: str
    question: str
    retrieved_sources: List[MinimalSource]


class MinimalAnswer(MinimalSearchResults):
    """Represents a generated answer together with its retrieved sources.

    This model extends the search result information by adding the answer
    generated by the language model.

    Attributes:
        answer: Generated answer text based on the retrieved context.
    """

    answer: str


class StudentSearchResults(BaseModel):
    """Represents a collection of retrieval results for dataset evaluation.

    This model stores the retrieval results obtained for multiple questions
    together with the retrieval parameter used.

    Attributes:
        search_results: List of retrieval results for each question.
        k: Number of sources requested during retrieval.
    """

    search_results: List[MinimalSearchResults]
    k: int


class StudentSearchResultsAndAnswer(BaseModel):
    """Represents a collection of generated answers and retrieval results.

    This model stores the complete output of the RAG pipeline, including the
    retrieved sources, generated answers, and retrieval configuration.

    Attributes:
        search_results: List of generated answers with their corresponding
            retrieved sources.
        k: Number of sources retrieved for each question.
    """

    search_results: List[MinimalAnswer]
    k: int
